2025-01-09 15:23:07,818 - src.point_cloud.webodm_client - ERROR - Point cloud generation failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/projects/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F91A56F4A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
